pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
  displayName: 'Use Python 3.7'

- script: |
    pip3 install -U pip setuptools
    pip3 install -r requirements_dev.txt -r requirements.txt . git+https://github.com/Abstract-Tech/pytest-azurepipelines.git
  displayName: 'Install derex.demo'

- script: nohup ddc pull &
  displayName: 'Pull edX image in background'

- script: |
    set -ex
    set -o pipefail
    cd tests
    pytest --ignore-docstrings |grep -v codecoveragetool=Cobertura
  displayName: 'Run python tests'

- script: |
    # We installed the package with pip, and coverage reports the full absolute path.
    # We cut to derex/demo/etc/etc
    DEREX_DEMO_PATH=`cd tests;python -c "from pathlib import Path; import derex.demo;print(Path(derex.demo.__file__).parent.parent.parent)"`
    echo Replacing ${DEREX_DEMO_PATH} in tests/htmlcov/*.html
    grep "${DEREX_DEMO_PATH}" tests/htmlcov/*.html
    sed -i -e "s|${DEREX_DEMO_PATH}||" tests/htmlcov/*.html
    npm install juice
    # Azure pipelines strips style sheets but leaves styles in place.
    # juice can embed the styles in the HTML for us and present a much better
    # view in the coverage results tab.
    for filename in tests/htmlcov/*.html; do $(npm bin)/juice $filename $filename; done
    echo "##vso[codecoverage.publish codecoveragetool=Cobertura;summaryfile=${PWD}/tests/test-cov.xml;reportdirectory=${PWD}/tests/htmlcov;]"
  displayName: Fix coverage result and publish it
  condition: succeededOrFailed()
